/**
 * Motion analysis types — schema for `*_motion.json` generated by
 * `scripts/analysis/analyze_motion.py`.
 *
 * The contract here MUST stay in lockstep with the Python writer; bump
 * `MOTION_SCHEMA_VERSION` and rename the file (or add a back-compat reader)
 * on breaking changes. See docs/motion-analysis-and-lesson-mode.md §1.
 */

export const MOTION_SCHEMA_VERSION = 2;

/** 8-direction quantization plus writer aggregate buckets. */
export type Cardinal8 =
  | 'up'
  | 'upRight'
  | 'right'
  | 'downRight'
  | 'down'
  | 'downLeft'
  | 'left'
  | 'upLeft'
  | 'still'
  | 'mixed';

/** Joints we currently track. Subset of MediaPipe Pose's 33-point layout. */
export type JointId =
  | 'leftWrist'
  | 'rightWrist'
  | 'leftElbow'
  | 'rightElbow'
  | 'leftAnkle'
  | 'rightAnkle';

export const CARDINAL8_VALUES = [
  'up',
  'upRight',
  'right',
  'downRight',
  'down',
  'downLeft',
  'left',
  'upLeft',
  'still',
  'mixed',
] as const satisfies readonly Cardinal8[];

export const JOINT_IDS = [
  'leftWrist',
  'rightWrist',
  'leftElbow',
  'rightElbow',
  'leftAnkle',
  'rightAnkle',
] as const satisfies readonly JointId[];

/** Map JointId → MediaPipe Pose landmark index. */
export const JOINT_LANDMARK_INDEX: Readonly<Record<JointId, number>> = {
  leftElbow: 13,
  rightElbow: 14,
  leftWrist: 15,
  rightWrist: 16,
  leftAnkle: 27,
  rightAnkle: 28,
};

export interface TrajectorySample {
  /** Frame time in seconds. */
  t: number;
  /** Position in the torso-normalized frame. */
  x: number;
  y: number;
  /** Smoothed velocity in the same frame. */
  vx: number;
  vy: number;
  /** sqrt(vx^2 + vy^2). */
  speed: number;
  /** Direction angle in degrees, 0..360, with the y-axis flipped so "up" maps to screen-up. */
  direction: number;
  /** Quantized 8-direction bucket; "still" when speed below the still threshold. */
  cardinal: Cardinal8;
  /** True when this sample is a local speed extremum (key frame). */
  isKeyFrame: boolean;
  /** MediaPipe visibility from the source pose; samples below the visibility threshold are skipped. */
  visibility: number;
}

export interface JointTrajectory {
  joint: JointId;
  /** Sparse: missing visibility frames omitted. Order matches frame time. */
  samples: TrajectorySample[];
  stats: {
    totalDistance: number;
    peakSpeed: number;
    speedVariance: number;
    /** Fraction of source frames that survived visibility filtering. */
    coverage: number;
  };
}

export interface MotionSegment {
  id: string;
  index: number;
  startTime: number;
  endTime: number;
  duration: number;
  emoji: string;
  title: string;
  description: string;
  primaryJoints: JointId[];
  primaryDirection: Cardinal8;
  difficulty: 1 | 2 | 3;
  keyFrames: number[];
  tips: string[];
  beatIndices?: number[];
  /** Optional LLM-polished copy; UI prefers this when present, falls back to `description`. */
  llmDescription?: string;
}

export interface MotionHint {
  /** When to show the hint, in seconds of the playback timeline. */
  triggerTime: number;
  segmentId: string;
  preview: string;
  cue: 'beatPrep' | 'directionArrow' | 'sectionStart';
  leadMs: number;
}

export interface JointBeatStats {
  distance: number;
  pathLength?: number;
  peakSpeed: number;
  cardinal: Cardinal8;
  visibility: number;
  angleDeg?: number;
}

export interface BeatAction {
  index: number;
  startTime: number;
  endTime: number;
  duration: number;
  segmentId?: string;
  primaryJoint: JointId;
  primaryDirection: Cardinal8;
  emoji: string;
  label: string;
  jointStats: Partial<Record<JointId, JointBeatStats>>;
  visibilityWarning?: 'lowFoot' | 'lowHand' | string;
}

export interface ArmPoseDetail {
  elbowAngleDeg: number;
  wristHeightBand: 'overhead' | 'high' | 'mid' | 'low' | string;
}

export interface LegPoseDetail {
  kneeBent: boolean;
  ankleSide: 'center' | 'outside' | 'inside' | string;
}

export interface LimbBeatSlice {
  beatIndex: number;
  startTime: number;
  endTime: number;
  cardinal: Cardinal8;
  emoji: string;
  distance: number;
  peakSpeed: number;
  armPose?: ArmPoseDetail;
  legPose?: LegPoseDetail;
}

export interface MotionSummary {
  primaryJoints: JointId[];
  dominantDirections: Array<{ cardinal: Cardinal8; share: number }>;
  bpm?: number;
  beatTimes?: number[];
}

export interface MotionExtractConfig {
  /** Frames between detection runs; matches the source pose extract_config when known. */
  stride: number;
  /** Smoothing window size in frames. */
  smoothingWindow: number;
  /** Speed below this (units per second) counts as `still`. */
  stillSpeedThreshold: number;
  /** Visibility below this is skipped from trajectory. */
  visibilityThreshold: number;
  /** Minimum segment duration in seconds. */
  minSegmentDuration: number;
  /** Maximum number of segments produced. */
  maxSegments: number;
}

export interface MotionAnalysis {
  schema_version: number;
  source_pose: string;
  fps: number;
  duration: number;
  extracted_at: string;
  extract_config: Partial<MotionExtractConfig>;
  trajectories: Partial<Record<JointId, JointTrajectory>>;
  limbs?: Partial<Record<JointId, LimbBeatSlice[]>>;
  beats: BeatAction[];
  segments: MotionSegment[];
  hints: MotionHint[];
  summary: MotionSummary;
}
